Repository DFE-Digital/fh-admin-service-testing, pull requests merged in 2023-08, with the labels that each got.

#45 Sprint stories , regression refactor , GHA
  .github/workflows/test-adminUi-regression.yml
  cypress/e2e/admin-service/pageSpecs/addPerm-dfeAdminHomepage.spec.js
  cypress/e2e/admin-service/pageSpecs/addPerm-errorPages.spec.js
  cypress/e2e/admin-service/pageSpecs/manVCS-ViewOrgPage.spec.js
  cypress/e2e/admin-service/pageSpecs/manVCS-addVcsConfirmPage.spec.js
  cypress/e2e/admin-service/pageSpecs/manVCS-manOrgsPage.spec.js
  cypress/support/commands.js
Labels: GHA, Voluntary community organisations (VCSs)

#51 adds tags - dfeAdmin
  cypress/e2e/001test.spec.js
  cypress/e2e/addPermissions/addPerm-dfeAdmin-homepage.spec.js
  cypress/e2e/addPermissions/addPerm-la-dfeAdmin-UserEmail.spec.js
  cypress/e2e/addPermissions/addPerm-la-dfeAdmin-UserName.spec.js
  cypress/e2e/addPermissions/addPerm-la-dfeAdmin-checkAnswerPage.spec.js
  cypress/e2e/addPermissions/addPerm-la-dfeAdmin-confirmationPage.spec.js
  cypress/e2e/addPermissions/addPerm-la-dfeAdmin-typeOfRole.spec.js
  cypress/e2e/addPermissions/addPerm-la-dfeAdmin-typeOfUserLA.spec.js
  cypress/e2e/addPermissions/addPerm-la-dfeAdmin-whichLA.spec.js
  cypress/e2e/addPermissions/addPerm-vcs-dfeAdmin-AddOrg.spec.js
  cypress/e2e/addPermissions/addPerm-vcs-dfeAdmin-UserEmail.spec.js
  cypress/e2e/addPermissions/addPerm-vcs-dfeAdmin-UserName.spec.js
  cypress/e2e/addPermissions/addPerm-vcs-dfeAdmin-addOrgCheckDetailsPage.spec.js
  cypress/e2e/addPermissions/addPerm-vcs-dfeAdmin-addOrgConfirmPage.spec.js
  cypress/e2e/addPermissions/addPerm-vcs-dfeAdmin-checkAnswerPage.spec.js
  cypress/e2e/addPermissions/addPerm-vcs-dfeAdmin-confirmationPage.spec.js
  cypress/e2e/addPermissions/addPerm-vcs-dfeAdmin-typeOfUserVCS.spec.js
  cypress/e2e/addPermissions/addPerm-vcs-dfeAdmin-whichLA.spec.js
  cypress/e2e/addPermissions/addPerm-vcs-dfeAdmin-whichVcsOrg.spec.js
  cypress/e2e/e2eTests/e2eTest001-dfeAdmin-addPerm-la-vcs.spec.js
  cypress/e2e/e2eTests/e2eTest002-dfeAdmin-addPerm-addVCSOrg.spec.js
  cypress/e2e/manageAccount/dfeAdmin-manageAccountPage.spec.js
  cypress/e2e/manageAccount/dfeAdmin-myAccountLink.spec.js
  cypress/e2e/managePermissions/manPerm-dfeAdmin-ConfirmPage.spec.js
  cypress/e2e/managePermissions/manPerm-dfeAdmin-managePermissionsPage.spec.js
  cypress/e2e/managePermissions/manPerm-dfeAdmin-userEmail.spec.js
  cypress/e2e/managePermissions/manPerm-dfeAdmin-userPermissions.spec.js
  cypress/e2e/manageVCSOrgs/manVCS-dfeAdmin-ViewOrgPage.spec.js
  cypress/e2e/manageVCSOrgs/manVCS-dfeAdmin-addVcsConfirmPage.spec.js
  cypress/e2e/manageVCSOrgs/manVCS-dfeAdmin-manOrgsPage.spec.js
  cypress/e2e/mobile-e2e-journeys/dfeAdmin-addPerm-la-e2ejourney-mobile.spec.js
  cypress/e2e/mobile-e2e-journeys/dfeAdmin-addPerm-vcs-e2ejourney-mobile.spec.js
  cypress/support/commands.js
Labels: Refactor Regression

#52 FHG-3870 LA mg-Who are you adding permissions for?
  cypress/e2e/addPermissions/addPerm-LAMan-typeOfRole.spec.js
Labels: Accounts - add permissions, LAManager

#56 Refactor regression
  cypress/support/LACommands.js
  cypress/support/VCSCommands.js
  cypress/support/accountsCommands.js
  cypress/support/commands.js
  cypress/support/e2e.js
Labels: Refactor Regression

#57 Pipeline switch
  config.json
  cypress.config.js
Labels: azure
